services:
  - type: web
    name: emogo-backend
    runtime: python
    plan: free
    autoDeploy: false
    envVars:
      - key: MONGODB_URI
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
